---GET
localhost:3000/person/{id}
localhost:3000/person
---DELETE
localhost:3000/person/{id}
---POST
---PUT
localhost:3000/person/{id}
{
  "document_number": "00000001",
  "name": "Example Name",
  "mail_address": "Example_123@gmail.com",
  "phone_number": "999999900",
  "type_document": "D",
  "gender": "F"
}
localhost:3000/project/{id}
{
    "managerid": {id},
    "name": "Test",
    "state": "ACTIVE",
    "start_date": "2022-09-04"
    "end_date": "2022-09-06"
}
localhost:3000/project/{id}/addtask/{taskid}
localhost:3000/project/{id}/addteammenber/{personid}
localhost:3000/project/{id}/deletetask/{taskid}
localhost:3000/project/{id}/deleteteammenber/{personid}
localhost:3000/task/{id}
{
    projectstageid = {id},
    managerid = {id},
    ownerid = {id}
    tasknotes: [
      "test note",
    ]
    taskstage: "PLANING",
    description: "TEST PLAN",
    type_task: "TASK",
    subject: "PLAN",
}
localhost:3000/task/{id}
{
    projectstageid = {id},
    managerid = {id},
    ownerid = {id}
    tasknotes: [
      "test note",
    ]
    taskstage: "PLANING",
    description: "TEST PLAN",
    type_task: "INCIDENT",
    subject: "PLAN",
}