---GET
localhost:3000/person/{id}
localhost:3000/person
---DELETE
localhost:3000/person/{id}
---POST
---PUT
localhost:3000/project/{id}/addtask/{taskid}
localhost:3000/project/{id}/addteammenber/{personid}
localhost:3000/project/{id}/deletetask/{taskid}
localhost:3000/project/{id}/deleteteammenber/{personid}
---PERSON
[
  {
    "_id": {
      "$oid": "6316126157e25a023e148c10"
    },
    "document_number": "00000001",
    "name": "Example Name",
    "mail_address": "Example_123@gmail.com",
    "phone_number": "999999900",
    "type_document": "D",
    "gender": "F"
  }
]
---PROJECT

[
  {
    "_id": {
      "$oid": "631619d9e87ba7a2b876f7ee"
    },
    "teams": [],
    "tasks": [],
    "name": "Test",
    "state": "ACTIVE",
    "start_date": "2022-09-04",
    "end_date": "2022-09-06",
    "stages": [
      "PLANNING",
      "DESIGN",
      "TODO",
      "TEST",
      "END"
    ],
    "types_task": [
      "TASK",
      "INCIDENT"
    ]
  }
]
---TASK
{
    "projectstageid": "631619d9e87ba7a2b876f7ee",
    "managerid": "6316126157e25a023e148c10",
    "ownerid": "6316126157e25a023e148c10",
    "notes": [
      "test note"
    ],
    "keywords":[
      "prueba"
    ],
    "taskstage": "PLANING",
    "description": "TEST PLAN",
    "type_task": "TASK",
    "subject": "PLAN"
}
http://localhost:3000/project/631619d9e87ba7a2b876f7ee/addtask/631629e41d72e62dbeb52e87
